### ISSUE TITLE
SAM v2 VMod 9.5.3 Goes Aligns on Destination first, then Aligns to Taxiing LCD on Undock

### ISSUE THREAD

**Issue by Saufen** [sugardose/SpaceEngineers#5]
# Steps to Reproduce
1. Create a SAM enabled Connector and configure an LCD screen to create a path. 
- I created one about 10 blocks away at the 3 o'clock position, looking down at the docked ship on the connector. 
2. Create an Orientation (ADD STANCE command) in SAM  about 300 m away. Orientate it so that it is in a different direction from the ship's nose when it docked to the Connector and the LCD screen. 
- I created an Orientation in the 9 o'clock position looking down at the docked ship on the connector.
3. Dock the ship at the SAM enabled Connector 
- (using SAM or not doesn't appear to make a difference).  
4. Move the cursor in the SAM LCD window to the Orientation and TOGGLE navigation.

# Actual Behavior
- SAM status in the LCD goes to "undocking ..." and the ship goes to docking height.
- SAM status goes to "aligning ..." and the ship changes it's orientation to point on the Orientation (destination).
- SAM status goes to "taxiing ... " and the ship changes it's orientation to point to the LCD screen and begins taxiing.
- After taxiing SAM aligns to the destination and heads on it's way.

# Expected Behavior
- SAM status in the LCD goes to "undocking ..." and the ship goes to docking height.
- SAM status goes to "taxiing ..." and the ship changes it's orientation to point to the LCD screen and begins taxiing.

# What I think is a Bug
SAM shouldn't align to the destination after undocking, then align back to the LCD that makes up the taxiing path. It should transition from Undocking and directly align with the TaxiIng LCD and begin Taxiing.

# Additional Information 
- SAM version: SAM v2 VMod 9.5.3 
- I did try another SAM enabled dock as my destination and observed the same "Actual Behavior". I don't think what type of location SAM is navigating has anything to do with the actual behavior, but didn't test too extensively.
- I don't think orientation of the ship to connector to LCD has anything to do with this behavior, but didn't test too extensively.
- I'm sending this here since I didn't see any other great place to submit a possible bug. I didn't have the chance to validate this on the newest (or any older) version of SAM v2 so I don't know if the same behavior is there as well.

**Comment by sugardose** [comment]
Thanks for the detailed report Saufen. I suggest trying the original SAMv2 to see if the same behaviour is experienced. SAM v2 VMod has some additional changes to the navigation code.

**Comment by SCBionicle** [comment]
Thanks for the info, I'll work on it as soon as I'm able (which should be within a few days). I actually knew about that bug, I just forgot to fix it.

**Comment by SCBionicle** [comment]
The issue should be fixed and is uploaded to the workshop. Can you verify that it's working?

**Comment by Saufen** [comment]
Thanks. I'll be able to verify this on Saturday. I'll send along an update at that time.

**Comment by Saufen** [comment]
@SCBionicle I'm still seeing the same behavior with SAMv2 vMod 9.5.4 (as reported by the Programmable Block in the Control Panel).

I select a SAM enabled connector at my 3'oclock with ship facing the LCD screen. I initiate the SELECT command. The ship goes to "undocking ...", then "aligning ..." to the destination, then "taxiing ...." and realigns on the LCD screen.

At this point, I'm not sure if this is on my end.

**Comment by SCBionicle** [comment]
@Saufen Could you send a copy of your saved game so I can more easily test the glitch?

**Comment by Saufen** [comment]
@SCBionicle A saved game that I recreated the issue in was uploaded to https://steamcommunity.com/sharedfiles/filedetails/?id=1962196296.

**Comment by SCBionicle** [comment]
Thank you, I'll look at it as soon as I am able.

**Comment by SCBionicle** [comment]
@Saufen I believe the issue is now fixed, please verify. Apparently I forgot to update the balancedDirection variable when in atmosphere, it should now work properly.

Thanks for providing that world, it helped out quite a bit.

**Comment by Saufen** [comment]
I can verify the issue is fixed running version SAM v2 vMod 9.5.5.

In the absence of any published process, I'm going to mark this as closed. Thanks.
